datab/datab/urls.py
from django.contrib import admin
from django.urls import path,include
from demo import views


urlpatterns = [
    path('',views.IndexView.as_view(),name='list'),
    path('admin/',admin.site.urls,name='admin'),
    path('demo/',include('demo.urls',namespace='demo')),
]

datab/demo/urls.py
from django.urls import path
from . import views

app_name = 'demo'

urlpatterns = [
    path('',views.DisasterListView.as_view(),name='list'),
    path('<int:pk>/',views.DisasterDetailView.as_view(),name='detail'),
    path('create/',views.DisasterCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.DisasterUpdateView.as_view(),name='update'),
    #path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete')
]

datab/demo/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime


class Disaster(models.Model):
    name = models.CharField(max_length=256)
    # each disaster will be assigned to an industry
    #industry = models.ForeignKey(Industry,related_name='industries',on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.name


class Industry(models.Model):
    name = models.CharField(max_length=256)
    owner = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    disaster = models.ForeignKey(Disaster,related_name='industries',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("demo:detail",kwargs={'pk':self.pk})

datab/demo/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                CreateView,DeleteView,
                                UpdateView)

import datetime
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self,**kwargs):
        context  = super().get_context_data(**kwargs)
        context['injectme'] = "Basic Injection! "
        return context

class DisasterListView(ListView):
    model = models.Disaster

class DisasterDetailView(DetailView):
    context_object_name = 'disaster_details'
    model = models.Disaster
    template_name = 'demo/disaster_detail.html'


class DisasterCreateView(CreateView):
    fields = ("name")
    model = models.Disaster

class DisasterUpdateView(UpdateView):
    fields = ("name","industry")
    model = models.Disaster

datab/demo/templates/demo/basic_app_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Data-B</title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-nav">
        <a class="navbar-brand" href="{% url 'demo:list' %}">Disasters</a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  {# Plugins#}

  <!-- Latest compiled and minified jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

datab/demo/templates/demo/disaster_detail.html
{% extends "demo/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>Disaster Details:</h2>
    <p>Name: {{disaster_details.name}}</p>
      {% for industry in disaster_details.industries.all %}
        <h3>Industry: Sugar Factory {{industry.name}}</h3>
        <p>Principal: {{industry.owner}}</p>
        <p>Location: {{industry.location}}</p>


        <p>Estimated number of humans in the facility: </p>
          <ul>
              <li>Basement: N1 </li>
              <li>Ground Floor: N2 </li>
              <li>First Floor: N3 </li>
          </ul>

        <p>HeatMap</p>

        <p>3D Reconstruction</p>

        <p>Location: {{industry.location}}</p>
      {% endfor %}


  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'demo:update' pk=disaster_details.pk %}">Update</a></p>
  </div>

{% endblock %}

datab/demo/templates/demo/disaster_form.html
{% extends "demo/basic_app_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create Disaster
  {% else %}
  Update Disaster
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

datab/demo/templates/demo/disaster_list.html
{% extends "demo/basic_app_base.html" %}
{% block body_block %}
  <div class="jumbotron">

    <h1>Last Disasters</h1>
      <ol>
        {% for disaster in disaster_list %}
          <h2><li><a href="{{disaster.id}}/">{{disaster.name}} </a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}

datab/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Data-B</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'datab/css/master.css'%}">
    </head>
    <body class='loader'>
        <div class="container mycontent">
            {% block content %}

            {% endblock %}
        </div>
    </body>
</html>

datab/templates/index.html
{% extends "base.html" %}

  {% block body_block %}
    <h1>Demo Guidelines</h1>
  {% endblock %}